[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_contract = "DeuVnP472sWYA1Dibw5oahUcFeq9g4eK8PRNbeKupDAy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rajeeb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
