[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "EsPFkJNfvFA5TJ6oN7V6oEtvaR7EAj1iRhHULEVF4XQA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rajeeb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
